version: "3"

services:
  dhcp:
    build: ./dhcp
    network_mode: host
    environment:
      SUBNET: "192.168.1.0"
      NETMASK: "255.255.255.0"
      ROUTERS: "192.168.1.1"
      RANGE_START: "192.168.1.11"
      RANGE_END: "192.168.1.99"
      NEXT_SERVER: "192.168.1.21"
  tftp:
    build: ./tftp
    network_mode: host
    volumes:
      - ./tftpboot:/var/lib/tftpboot
  nginx:
    build: ./nginx
    network_mode: host
    volumes:
      - ./mnt:/usr/share/nginx/html/CentOS
      - ./kickstart:/usr/share/nginx/html/kickstart
    environment:
      NGINX_PORT: 80
